// Actors: "Min-sik Choi, Ji-Tae Yoo, Hye-jeong Kang, Dae-han Ji"
// Awards: "40 wins & 18 nominations."
// BoxOffice: "$637,778"
// Country: "South Korea"
// DVD: "23 Aug 2005"
// Director: "Chan-wook Park"
// Genre: "Action, Drama, Mystery, Thriller"
// Language: "Korean"
// Metascore: "77"
// Plot: "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days."
// Poster: "https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_SX300.jpg"
// Production: "Tartan Films"
// Rated: "R"
// Ratings: Array(3)
// 0: {Source: "Internet Movie Database", Value: "8.4/10"}
// 1: {Source: "Rotten Tomatoes", Value: "82%"}
// 2: {Source: "Metacritic", Value: "77/100"}
// length: 3
// __proto__: Array(0)
// Released: "21 Nov 2003"
// Response: "True"
// Runtime: "120 min"
// Title: "Oldboy"
// Type: "movie"
// Website: "N/A"
// Writer: "Garon Tsuchiya (story), Nobuaki Minegishi (comic), Chan-wook Park (character created by: Oldboy,  Vengeance Trilogy), Chan-wook Park (screenplay), Joon-hyung Lim (screenplay), Jo-yun Hwang (screenplay)"
// Year: "2003"
// imdbID: "tt0364569"
// imdbRating: "8.4"
// imdbVotes: "495,869"

// Actors: "Ron Perlman, John Hurt, Selma Blair, Rupert Evans"
// Awards: "3 wins & 23 nominations."
// BoxOffice: "$59,035,104"
// Country: "USA"
// DVD: "27 Jul 2004"
// Director: "Guillermo del Toro"
// Genre: "Action, Fantasy, Horror"
// Language: "English, Russian"
// Metascore: "72"
// Plot: "A demon, raised from infancy after being conjured by and rescued from the Nazis, grows up to become a defender against the forces of darkness."
// Poster: "https://m.media-amazon.com/images/M/MV5BNTc1ZWY0ZTEtZTVmNi00MTg0LTg4NmQtZTI4OWNiMmQ0MWZkXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg"
// Production: "Sony Pictures"
// Rated: "PG-13"
// Ratings: (3) [{…}, {…}, {…}]
// Released: "02 Apr 2004"
// Response: "True"
// Runtime: "122 min"
// Title: "Hellboy"
// Type: "movie"
// Website: "N/A"
// Writer: "Guillermo del Toro (screenplay), Guillermo del Toro (screen story), Peter Briggs (screen story), Mike Mignola (comic books)"
// Year: "2004"
// imdbID: "tt0167190"
// imdbRating: "6.8"
// imdbVotes: "301,177"
// __proto__: Object